# Generated by Django 4.1.1 on 2023-10-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogin',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='userlogin',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='userregister',
            name='is_superuser',
        ),
    ]
